baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Luminal's Blog"
theme = 'rusty-typewriter'

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Luminal'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'About'
pageRef = '/about.md'
weight = 3

[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS","SearchIndex"]
